import type { Metadata } from "next";
import "@/styles/global.css";
import { headers } from 'next/headers'
import ContextProvider from "@/components/auth/ContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headersObj = await headers();
const cookies = headersObj.get('cookie')

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ContextProvider cookies={cookies}>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
