import { config, library } from "@fortawesome/fontawesome-svg-core";
import { 
  faHome, 
  faSync,
  faPlus,
  faEdit,
  faTrash,
  faEye,
  faFolder,
  faSort,
  faFilter,
  faEllipsisV,
  faUpload,
  faXmark,
  faDownload,
  faShare,
  faPencil,
  faChevronDown,
  faFolderPlus,
  faFileCirclePlus,
  faExclamationTriangle,
  faFile,
  faUpRightFromSquare,
  faCheck,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
  faHome, 
  faSync, 
  faPlus, 
  faEdit, 
  faTrash, 
  faEye, 
  faFolder, 
  faSort, 
  faFilter, 
  faEllipsisV, 
  faUpload, 
  faXmark, 
  faDownload, 
  faShare, 
  faPencil,
  faChevronDown,
  faFolderPlus,
  faFileCirclePlus,
  faExclamationTriangle,
  faFile,
  faUpRightFromSquare,
  faCheck,
  faWrench,
);
